### ISSUE TITLE
No example for addlog command

### ISSUE THREAD

**Issue by jeanyang04** [AY2425S1-CS2103T-W13-3/tp#202]
![image](https://github.com/user-attachments/assets/0dc0ff45-77c3-45c3-9996-0525524fcde2)

Improvement: Add examples like add command

**Comment by zhiyi12345** [comment]
<img width="736" alt="Screenshot 2024-11-04 at 2 00 53 AM" src="https://github.com/user-attachments/assets/aae107ac-4532-429f-a99e-823e225a28bd">
Not sure if you are using the newest version of code to test, but on my end I could see the example once you scroll down.
Perhaps we should make this command box bigger, so that user dont need to use a mouse?

**Comment by jeanyang04** [comment]
Oh my bad... I thought it was unscrollable... I do think we can make the box slightly larger if possible
