### ISSUE TITLE
Bug: UI for Patient list not listing person 

### ISSUE THREAD

**Issue by zhiyi12345** [AY2425S1-CS2103T-W13-3/tp#206]
https://github.com/user-attachments/assets/50beb8b1-c9fe-442d-b4a8-d2f1f181cf4f

UI not showing anyone even though there are people present in the contact list.

**Comment by t-leongchuan** [comment]
Issue is due to a null-pointer Exception.
![image](https://github.com/user-attachments/assets/b86a82c6-0876-495d-af6b-e42574be18e2)

More specifically,
![image](https://github.com/user-attachments/assets/711ddfc3-bbb8-4e92-a597-d78fc00165b6)
We have an FXML annotation pointing to a Label with id `status`, but it does not exist in the `PersonListCard.fxml` file:
![image](https://github.com/user-attachments/assets/b12d57ac-4f5f-41c4-abab-6fc976bd5298)

The fix is to just add a Label element with id `status`.
![image](https://github.com/user-attachments/assets/f2cbf953-5c75-451f-83fb-5f5b785059d9)
